language: c
sudo: false
cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.cabal/packages
    - $HOME/tools
before_cache:
  - rm -f $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
before_install: source travis/setup.sh
install: travis/install.sh
script: travis/script.sh
matrix:
  include:
    - env: GHCVER=8.0.2 CABALVER=1.24 ROOT=1
      compiler: ": #GHC 8.0.2"
      addons: {apt: {packages: [cabal-install-1.24, ghc-8.0.2, alex-3.1.7, happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=8.2.1 CABALVER=2.0
      compiler: ": #GHC 8.2.1"
      addons: {apt: {packages: [cabal-install-2.0, ghc-8.2.1, alex-3.1.7, happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=head CABALVER=head ALLOW_NEWER="template-haskell"
      compiler: ": #GHC head"
      addons: {apt: {packages: [cabal-install-head, ghc-head, alex-3.1.4, happy-1.19.5], sources: [hvr-ghc]}}
  allow_failures:
    - compiler: ": #GHC head"
  fast_finish: true
