flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/reflex-frp/reflex
    commit: a1092192c61f3dec924a8e2686dfe3440681bab3
  extra-dep: true
extra-deps:
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
resolver: lts-8.22
